# Generated by Django 4.1.4 on 2023-01-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_adress_delete_task_alter_flowers_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adress',
            options={'verbose_name': 'Адрес', 'verbose_name_plural': 'Адреса'},
        ),
        migrations.AlterField(
            model_name='adress',
            name='task',
            field=models.CharField(max_length=11, verbose_name='номер телефона'),
        ),
        migrations.AlterField(
            model_name='adress',
            name='title',
            field=models.TextField(verbose_name='адрес'),
        ),
    ]
