# Generated by Django 4.1.4 on 2023-01-27 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_addresses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adress',
        ),
    ]
