# Generated by Django 4.1.5 on 2023-02-03 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleForOrd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Артикул покупки',
                'verbose_name_plural': 'Артикулы покупок',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Flows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('color', models.CharField(max_length=30, verbose_name='Цвет')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('photo', models.ImageField(upload_to='article/', verbose_name='Фото')),
                ('content', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('is_published', models.BooleanField(default=True, verbose_name='Выставить')),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, verbose_name='Остаток на складе')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
            ],
            options={
                'verbose_name': 'Цветы',
                'verbose_name_plural': 'Цветы',
                'ordering': ['time_create'],
            },
        ),
        migrations.DeleteModel(
            name='Flowers',
        ),
        migrations.AddField(
            model_name='articleforord',
            name='flows',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.flows', verbose_name='Цветы'),
        ),
        migrations.AddField(
            model_name='articleforord',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.orders'),
        ),
    ]
